spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: productos
            uri: http://productos:8082
            predicates:
              - Path=/api/productos/**

          - id: ventas
            uri: http://ventas:8083
            predicates:
              - Path=/api/ventas/**

server:
  port: 8080