spring.application.name=EvaRetail
server.port=8082

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Cambiar a ruta absoluta de tu pc Wallet en EV3-RETAIL
spring.datasource.url=jdbc:oracle:thin:@evretail_high?TNS_ADMIN=/wallet
spring.datasource.username=admin
spring.datasource.password=DuocRetail2026

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


springdoc.api-docs.path=/api-productos
springdoc.swagger-ui.path=/swagger-ui.html